- hosts: jenkins_server 
  vars:
     jenkins_home: "/opt/jenkins"
     jenkins_user: "jenkins"
     java_version: "java-1.8.0-openjdk"  
  tasks:
  - name: Coping templates
    template:
      src: jenkins.service.j2
      dest: /etc/systemd/system/jenkins.service
    become: yes
  - name: Install java
    yum: 
      name: "{{java_version}}"
      state: latest
    become: yes
  - name: Create group for user
    group:
      name: "{{jenkins_user}}"
    become: yes
  - name: User create
    user:
      name: "{{jenkins_user}}"
      groups: "{{jenkins_user}}"
    become: yes
  - name: Creating Directory
    file:
      path: "{{jenkins_home}}"
      state: directory
    become: yes
  - name: Download jenkins
    get_url:
      url: http://mirrors.jenkins.io/war-stable/latest/jenkins.war
      dest: '{{jenkins_home}}/jenkins.war'
    become: yes
  - name: Starting service
    systemd:
      name: jenkins
      state: started
      enabled: yes
    become: yes
  - name: Wait for starting Jenkins
    wait_for:
      port: "{{hostvars['jenkins_server'].app_port}}"
      host: "{{ansible_host}}"
      delay: 5

- hosts: httpd_server 
  vars:
    jenkins_ip: "{{hostvars['jenkins_server'].ansible_host}}"
    jenkins_port: "{{hostvars['jenkins_server'].app_port}}"
    check_port: "{{hostvars['httpd_server'].web_port}}"
  tasks:
  - name: Install httpd
    yum:
      name: httpd
      state: latest
    become: yes
  - name: Add virtual host
    template: 
      src: jenkins.conf.j2
      dest: /etc/httpd/conf.d/jenkins.conf
    become: yes
  - name: Start service
    service:
      name: httpd
      state: started
      enabled: yes
    become: yes
  - name: Check state
    wait_for:
      port: "{{check_port}}"
      host: "{{ansible_host}}"
