- name: Install httpd
  yum:
    name: httpd
    state: latest
  become: yes

- name: Add virtual host
  template: 
    src: jenkins.conf.j2
    dest: /etc/httpd/conf.d/jenkins.conf
  become: yes
  notify: "restart httpd"  

- name: Collect facts
  shell: httpd -v | grep version | awk -F\/ '{print $2;}' | cut -d " " -f1
  register: httpd_version
  changed_when: False
  become: true

- name: Include task to write facts
  include_tasks: "{{write_facts_task}}"
  vars:
    template: httpd.fact.j2
    mode: 'a+x'

- name: Sanity checks
  include_role:
    name: sanity
  tags:
    - never
    - httpd
    - sanity
