- hosts: webservers

  roles:
    - user
    - httpd

  tasks:
    - include_role:
        name: sanity
        tasks_from: httpd

- hosts: appservers  
  
  roles:
    - java
    - jenkins
  tasks:
    - include_role:
        name: sanity
        tasks_from: java

    - include_role:
        name: sanity
        tasks_from: jenkins
       
