- block:
  - name: "Check Service State"
    wait_for:
      port: "{{service_port}}"
      host: "{{ansible_host}}"
      timeout: "{{timeout_check}}"
      state: started
    become: yes


  rescue:
  - name: Start service
    systemd:
      name: "{{service}}"
      state: restarted
      enabled: yes
    become: yes
  
  always:
  - name: Show state
    command: systemctl status {{service}}
    changed_when: false
    become: yes
  tags: sanity
