- name: Restart/Start Jenkins
  systemd:
    name: jenkins
    daemon-reload: yes
    state: started 
    enabled: yes
  become: yes
  listen: "start service"

- name: Wait for starting Jenkins
  wait_for:
    port: "{{app_port}}"
    host: "{{ansible_host}}"
    delay: 5
  listen: "check state"

    
