- name: Import Create user 
  include_tasks: create_user.yml

- name: Forward key
  authorized_key:
    user: "{{ user }}"
    key: "{{ lookup('file', '{{ key_path }}/id_rsa.pub') }}"
  become: yes
  when: create_home == true

- name: Add to sudoers
  template:
    src: sudoers.j2
    dest: /etc/sudoers.d/{{ user }}
    validate: '/usr/sbin/visudo -cf %s'
    mode: 0440
    group: root
    owner: root
  become: yes
  when:  sudo == true
 

- name: Include task to write facts
  include_tasks: "{{write_facts_task}}"
  vars: 
    template: user.fact.j2

