- name: Install java
  yum: 
    name: java-{{ java_version }}-openjdk
    state: latest
  become: yes

- name: Verify Java installation
  shell: java -version 2>&1 | grep version | awk -F\" '{print $2;}' | cut -d"_" -f1
  notify: "verify java"
  become: yes
  register: java_play_version
  
- name: Create Directory fo Facts
  file:
    path: /etc/ansible/facts.d/
    state: directory
  become: yes

- name: Write facts
  template:
    src: java.j2
    dest: /etc/ansible/facts.d/java.fact
  become: yes
