- name: Create group
  group:
    name: "{{ group }}"
    gid: "{{ gid }}"
  become: yes

#- name: Debug  
#  debug: msg={{ home_dir }}

- name: Create user
  user:
    name: "{{ user }}"
    uid: "{{ uid }}"
    group: "{{ group }}"
    groups: "{{ groups_to_add | default(omit) }}"
    create_home: "{{ create_home | bool }}"
    home: "{{ home_dir | default(omit) }}"  
  become: yes

- name: Forward key
  authorized_key:
    user: "{{ user }}"
    key: "{{ lookup('file', '{{ key_path }}/id_rsa.pub') }}"
  become: yes
  when: create_home == "yes" 


- name: Add to sudoers
  template:
    src: sudoers.j2
    dest: /etc/sudoers.d/{{ user }}
    validate: '/usr/sbin/visudo -cf %s'
    mode: 0440
    group: root
    owner: root
  become: yes
  when:  sudo == "yes" 

- name: Create facts dir
  file:
    path: /etc/ansible/facts.d/
    state: directory
  become: yes

- name: Write facts
  template:
    src: user.j2
    dest: /etc/ansible/facts.d/user.fact
  become: yes



