- hosts: all 
  
  pre_tasks:
    - name: Install packages
      yum: 
        name: "{{common_package}}"
        state: latest
      become: yes

    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo
      become: yes

    - name: Enable Docker Edge & Test repo
      ini_file:
        dest: /etc/yum.repos.d/docer-ce.repo
        section: "{{ item }}"
        option: enabled
        value: 0
      become: yes
      with_items: 
        - 'docker-ce-test'
        - 'docker-ce-edge'

    - name: Install Docker
      yum: 
        name: docker-ce
        state: latest
      become: yes
    
    - name: User add
      user:
        name: vagrant
        append: yes
        groups: docker
      become: yes 

    - name: Create dir
      file: 
        path: /etc/docker
        state: directory
      become: yes
 
    - name: Copy file
      copy:
        src: daemon.json
        dest: /etc/docker/daemon.json
      become: yes
   
    - name: Docker start
      systemd:
        state: restarted
        name: "{{item}}"
        enabled: yes
        daemon-reload: yes
      with_items:
        - docker
        - ntpd
      become: yes

  tasks: 
    - name: Add kubenetes repo
      copy:
        src: kubernetes.repo
        dest: /etc/yum.repos.d/kubernetes.repo
      become: yes

    - name: 
      yum:
        name: "{{item}}"
        #disable_excludes: kubernetes
      with_items:
        - kubelet
        - kubeadm
        - kubectl
      become: yes 

    - name: Copy file
      copy:
        src: k8s.conf
        dest: /etc/sysctl.d/k8s.conf
      become: yes
     
    - name: Disable swap
      command: swapoff -a
      become: yes
    
    - name: Comment fstab
      command: sed -e '/\/dev\/mapper\/centos-swap/ s/^#*/#/' -i /etc/fstab
      become: yes

  post_tasks:    
    - name: Change IP in /etc/sysconfig/kubelet
      command: sed "s/\(KUBELET_EXTRA_ARGS=\).*/\1--node-ip=$(ifconfig enp0s8 | sed -n '2p' | awk '{print $2}')/" /etc/sysconfig/kubelet
      become: yes
    

    - name: Reload sysctl
      command: sysctl --system
      become: yes 

    - name: Kebelet start
      systemd:
        state: restarted
        name: kubelet
        enabled: yes
        daemon-reload: yes
      become: yes


##kubeadm init \
# --pod-network-cidr 10.244.0.0/16 \
# --apiserver-advertise-address ${IPADDR}
 
  
