- name: Test
  hosts: all
  
  roles:
    - common
    - devops_user

- name: Jenkins Install
  hosts: jenkins_server
  
  roles:
    - jenkins

- name: HTTPD Config and Install     
  hosts: httpd_server
  
  roles:
    - role: httpd
      ip_address: "{{hostvars['jenkins_server'].ansible_host}}"
      
