- name: System update
  yum: name=* state=latest
  notify: "clean packages"
  become: yes

- name: Install neсуssary tools
  yum:
    name: "{{ packages }}"
    state: latest
  notify: "clean packages"
  become: yes

- name: Create Directory
  file:
    path: /etc/ansible/facts.d/
    state: directory
  become: yes
